vmsingle:
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - vmsingle.apatsev.org.ru

grafana:
  ingress:
    ingressClassName: nginx
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - grafana.apatsev.org.ru
