apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: sentry-clickhouse
  namespace: clickhouse
spec:
  configuration:
    users:
      default/networks/ip:
        - "0.0.0.0/0"
      clickhouse_operator/password: "clickhouse_operator_password"
      clickhouse_operator/networks/ip:
        - "0.0.0.0/0"
    files:
      config.d/init-sentry.xml: |
        <clickhouse>
          <startup_scripts>
            <scripts>
              <query>CREATE DATABASE IF NOT EXISTS sentry</query>
            </scripts>
          </startup_scripts>
        </clickhouse>
      config.d/prometheus.xml: |
        <clickhouse>
          <prometheus>
            <endpoint>/metrics</endpoint>
            <port>9363</port>
            <metrics>true</metrics>
            <events>true</events>
            <asynchronous_metrics>true</asynchronous_metrics>
          </prometheus>
        </clickhouse>
    clusters:
      - name: sentry-cluster
        layout:
          shardsCount: 1
          replicasCount: 3
        templates:
          podTemplate: clickhouse
          serviceTemplate: clickhouse-metrics
          volumeClaimTemplate: data-volume
    zookeeper:
      nodes:
        - host: chk-sentry-keeper-sentry-keeper-0-0.clickhouse.svc.cluster.local
          port: 2181
        - host: chk-sentry-keeper-sentry-keeper-0-1.clickhouse.svc.cluster.local
          port: 2181
        - host: chk-sentry-keeper-sentry-keeper-0-2.clickhouse.svc.cluster.local
          port: 2181
  templates:
    podTemplates:
      - name: clickhouse
        spec:
          containers:
            - name: clickhouse
              image: altinity/clickhouse-server:25.3.8.10042.altinitystable
              resources:
                requests:
                  cpu: 1000m
                  memory: 4Gi
                limits:
                  cpu: 1000m
                  memory: 4Gi
              ports:
                - name: prometheus
                  containerPort: 9363
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      clickhouse.altinity.com/chi: sentry-clickhouse
                  topologyKey: kubernetes.io/hostname
    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
    serviceTemplates:
      - name: clickhouse-metrics
        spec:
          ports:
            - name: prometheus
              port: 9363
          type: ClusterIP
  defaults:
    replicasUseFQDN: "true"
    templates:
      podTemplate: clickhouse
      dataVolumeClaimTemplate: data-volume
