apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: sentry-clickhouse
  namespace: clickhouse
spec:
  configuration:
    users:
      default/networks/ip:
        - "0.0.0.0/0"
      clickhouse_operator/password: "clickhouse_operator_password"
      clickhouse_operator/networks/ip:
        - "0.0.0.0/0"
    clusters:
      - name: sentry-cluster
        layout:
          shardsCount: 1
          replicasCount: 3
        templates:
          podTemplate: clickhouse
          volumeClaimTemplate: data-volume
    zookeeper:
      nodes:
        - host: chk-clickhouse-keeper-keeper-cluster-0-0.clickhouse.svc.cluster.local
          port: 2181
        - host: chk-clickhouse-keeper-keeper-cluster-0-1.clickhouse.svc.cluster.local
          port: 2181
        - host: chk-clickhouse-keeper-keeper-cluster-0-2.clickhouse.svc.cluster.local
          port: 2181
  templates:
    podTemplates:
      - name: clickhouse
        spec:
          containers:
            - name: clickhouse
              image: altinity/clickhouse-server:25.3.6.10034.altinitystable
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      clickhouse.altinity.com/chi: sentry-clickhouse
                  topologyKey: kubernetes.io/hostname
    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
  defaults:
    replicasUseFQDN: "true"
    templates:
      podTemplate: clickhouse
      dataVolumeClaimTemplate: data-volume
