---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: sentry-prometheus-exporter
  namespace: sentry
spec:
  selector:
    matchLabels:
      app: sentry-prometheus-exporter
  endpoints:
    - port: metrics
      path: /metrics
