apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: delay-clickhouse
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - clickhouse
  delay:
    latency: '200ms'
    jitter: '50ms'
  direction: to
  target:
    selector:
      namespaces:
        - sentry
  duration: '5m'
