apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-sentry-web
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - sentry
    labelSelectors:
      app.kubernetes.io/component: web
  scheduler:
    cron: '@every 5m'
